import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";

export default function Home() {
  const onButtonClickHandler = () => {
    console.log("button pressed");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Core</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="Find shops nearby "
          onClickHandler={onButtonClickHandler}
        />

        <div className={styles.grid}></div>
      </main>
    </div>
  );
}
